### ISSUE TITLE
我想问一下多中心redis集群。数据实时同步那种方式

### ISSUE THREAD

**Issue by hadoop835** [bilibili/overlord#109]

**Comment by wayslog** [comment]
多中心 redis 实现上有问题。

1. 不能成环，也就是说，不能存在多写，只有单向同步可用。多向同步会造成网络风暴。
2. 网络环境差，可能造成同步延迟非常大，因此redis要额外保持一个超大的buffer来维持。
3. 不能用 redis cluster 方案，还是因为网络原因，波动较大的情况下 gossip 协议表现非常差。

因此，建议采取一写N读方式，并且用 https://github.com/vipshop/redis-migrate-tool 进行数据同步。
