### ISSUE TITLE
overlord 在后面为 redis 和 redis-cluster 的时候，是否支持 pipeline

### ISSUE THREAD

**Issue by dongkun-nb** [bilibili/overlord#141]
overlord 在后面为 redis 和 redis-cluster 的时候，是否支持 pipeline

**Comment by dongkun-nb** [comment]
经过测试，发现支持 pipeline 不支持 transaction

**Comment by wayslog** [comment]
必然是不支持的。。。因为没法保证 exec 命令里的 key 都在一个节点上。
