### ISSUE TITLE
[ERROR] Redis Cluster all seed nodes fail to fetch

### ISSUE THREAD

**Issue by wyaopeng** [bilibili/overlord#165]
启动的时候报错，如下
[ERROR] Redis Cluster fail to fetch error:fetcher CLUSTER NODES bad reply type
请问这个我需要怎么调整？

**Comment by wayslog** [comment]
你配置的后端和你选用的协议是否一致?
报这个错的话你的后端用的应该是 redis cluster, 但没能通过 `CLUSTER  NODES` 命令得到正确的返回值.你自己用 redis-cli 工具随便连个节点发这个命令试试看得到什么?

常见异常:
1. toml 里配置用 redis cluster 来连接非 redis cluster 集群(twemproxy或者单例)
2. 后端集群异常: 例如直接用 redis-cli 请求后端节点, 返回 -ERR cluster down
