### ISSUE TITLE
资源注入问题

### ISSUE THREAD

**Issue by 360CodeSafe** [bilibili/overlord#65]
此处的host和port来源与http请求，被直接用于网络访问的地址，可构成资源注入入侵内网系统。

https://github.com/bilibili/overlord/blob/c3074bfc58b41a001d0841b1c8e4da003ca98236/platform/api/server/command.go#L13-L18

也许是内部使用的系统不用考虑这些？如果是请忽略。

**Comment by luvletter1205** [comment]
有点酷o

**Comment by PSilverQ** [comment]
overload还行~
